# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [3]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [4]:
df = pd.read_csv('../output_data/cities.csv')
df

,City,Country,Latitude,Longitude,Date,Temperature,Maximum Tempurature,Humidity,Cloudiness,Wind Speed
0,rheinau,DE,48.87,8.20,1.585543e+09,33.656,35.996,59.0,90.0,13.920
1,kavieng,PG,-2.57,150.80,1.585543e+09,82.004,82.004,76.0,96.0,2.912
2,bengkulu,ID,-3.80,102.27,1.585543e+09,83.570,83.570,72.0,100.0,7.392
3,saint anthony,US,45.02,-93.22,1.585543e+09,41.378,44.996,45.0,1.0,5.760
4,west bay,KY,19.37,-81.42,1.585543e+09,78.710,78.998,94.0,20.0,5.760
...,...,...,...,...,...,...,...,...,...,...
585,seymchan,RU,62.88,152.43,1.585543e+09,19.292,19.292,86.0,19.0,4.800
586,muli,MV,2.92,73.57,1.585543e+09,83.318,83.318,61.0,53.0,1.904
587,medea,DZ,36.26,2.75,1.585543e+09,42.800,42.800,100.0,20.0,3.248
588,namatanai,PG,-3.67,152.43,1.585543e+09,84.020,84.020,74.0,83.0,6.720
589,praia,CV,14.92,-23.51,1.585543e+09,69.800,69.800,83.0,20.0,8.160

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [5]:
gmaps.configure(api_key = g_key)

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in narrowed_city_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display Map